config/routes.rb
R20130214Cookbook::Application.routes.draw do
  resources :books, :ingredients, :recipes
  root :to => 'books#index'
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :title, :cuisine, :chef, :image, :recipe_ids
  has_many  :recipes
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  servingsize  :integer
#  instructions :text
#  image        :text
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :servingsize, :instructions, :image, :book_id
  belongs_to  :book
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  def new
    @book = Book.new
  end
  def show
    @book = Book.find(params[:id])
  end
  def create
    book = Book.create(params[:book])
    redirect_to(book)
  end
  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to(book)
  end
  def edit
    @book = Book.find(params[:id])
  end
  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(books_path)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  def new
    @ingredient = Ingredient.new
  end
  def show
    @ingredient = Ingredient.find(params[:id])
  end
  def create
    ingredient = Ingredient.create(params[:ingredient])
    redirect_to(ingredient)
  end
  def update
    ingredient = Ingredient.find(params[:id])
    ingredient.update_attributes(params[:ingredient])
    redirect_to(ingredient)
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients_path)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  def new
    @recipe = Recipe.new
  end
  def show
    @recipe = Recipe.find(params[:id])
  end

  def create
    recipe = Recipe.create(params[:recipe])
    redirect_to(recipe)
  end
  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe)
  end
  def edit
    @recipe = Recipe.find(params[:id])
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipe_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
<%= f.text_field :title, :autofocus => true %>
<%= f.label :title, "Book Title" %><br>
<%= f.text_field :cuisine %>
<%= f.label :cuisine %><br>
<%= f.text_field :chef %>
<%= f.label :chef %><br>
<%= f.text_field :image %>
<%= f.label :image %><br>

<% Recipe.order(:name).each do |recipe| %>
  <span><%= recipe.name %></span>
  <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes) %>
<% end %>
<br>
<%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<h2>Edit Book</h2>

  <%= render :partial => "form" %>

app/views/books/index.html.erb
<%= link_to("New Book", new_book_path, :class => "right") %>
<ol>
  <% @books.each do |book| %>
  <li>
    <ul>
      <li><%= link_to(book.title, book) %></li>
      <li><%= book.chef %></li>
      <li><%= image_tag(book.image) %></li>
    </ul>
  </li>
  <% end %>
</ol>

app/views/books/new.html.erb
<h2>New Book</h2>

  <%= render :partial => "form" %>

app/views/books/show.html.erb
<%= link_to 'Edit Book', edit_book_path(@book), :class => "right" %>
<%= link_to 'Delete', @book, :method => :delete, :class => "right", :confirm => "You sure?" %>

<h2><%= @book.title %></h2>
<%= @book.chef %><br>
<%= image_tag(@book.image) %><br>
<br>
<hr>
<% @book.recipes.each do |recipe| %>
  <h2><%= link_to(recipe.name, recipe) %></h2>
  <%= image_tag(recipe.image) %>
  <h3>Ingredients:</h3>
  <% recipe.ingredients.each do |ingredient| %>
      <%= ingredient.name %>
      <%= image_tag(ingredient.image, :size => "100x100") %>
  <% end %>
  <hr>
<% end %>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
<%= f.text_field :name, :autofocus => true %>
<%= f.label :name %><br>
<%= f.text_field :measurement %>
<%= f.label :measurement %><br>
<%= f.text_field :cost %>
<%= f.label :cost %><br>
<%= f.text_field :image %>
<%= f.label :image %><br>
<%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<h2>Edit Ingredient</h2>

<%= render :partial => "form" %>

app/views/ingredients/index.html.erb
<%= link_to("New Ingredient", new_ingredient_path, :class => "right") %>

<% @ingredients.each do |ingredient| %>
  <h3><%= link_to(ingredient.name, ingredient) %></h3>
  <p>Measurement:  <%= ingredient.measurement %></p>
  <p>Cost:  $<%= ingredient.cost %></p>
  <%= image_tag(ingredient.image, :size => "520x340") %>
<% end %>

app/views/ingredients/new.html.erb
<h2>New Ingredient</h2>

<%= render :partial => "form" %>

app/views/ingredients/show.html.erb
<%= link_to 'Edit', edit_ingredient_path(@ingredient), :class => "right" %>
<%= link_to 'Delete', @ingredient, :method => :delete, :class => "right", :confirm => "You sure?" %>

<%= @ingredient.name %><br>
<%= @ingredient.measurement %><br>
$<%= @ingredient.cost %><br>
<%= image_tag(@ingredient.image) %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookin' Mama</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
  <nav>
    <ul>
     <li><span><%= link_to("Books", books_path) %></span></li>
     <li><span><%= link_to("Recipes", recipes_path) %></span></li>
     <li><span><%= link_to("Ingredients", ingredients_path) %></span></li>
    </ul>
  </nav>
    <h1>Cookin' Mama  </h1>
    <%= image_tag('lady.png', :size => '150x145') %>
  </header>
  <div id="page-container">


  <section>
    <%= yield %>
  </section>
  </div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
<%= f.text_field :name, :autofocus => true %>
<%= f.label :name %><br>
<%= f.text_field :course %>
<%= f.label :course %><br>
<%= f.text_field :cooktime %>
<%= f.label :cooktime %><br>
<%= f.text_field :servingsize %>
<%= f.label :servingsize %><br>
<%= f.text_field :instructions %>
<%= f.label :instructions %><br>
<%= f.text_field :image %>
<%= f.label :image %><br>

<% Ingredient.order(:name).each do |ingredient| %>
  <span><%= ingredient.name %></span>
  <%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients) %>
<% end %>
<br>

<%= f.submit %>
<% end %>

app/views/recipes/edit.html.erb
<h2>Edit Recipe</h2>

<%= render :partial => "form" %>

app/views/recipes/index.html.erb
<%= link_to("New Recipe", new_recipe_path, :class => "right") %>

<% @recipes.each do |recipe| %>
  <h3><%= link_to(recipe.name,recipe) %></h3>
  <p>Course:  <%= recipe.course %></p>
  <p>Cooking time:  <%= recipe.cooktime %> minutes</p>
  <p>Serves:  <%= recipe.servingsize %> </p>
  <p>Instructions: <%= recipe.instructions %></p>
  <%= image_tag(recipe.image, :size => "520x340") %>
<% end %>

app/views/recipes/new.html.erb
<h2>New Recipe</h2>

<%= render :partial => "form" %>

app/views/recipes/show.html.erb
<%= link_to 'Edit', edit_recipe_path(@recipe), :class => "right" %>
<%= link_to 'Delete', @recipe, :method => :delete, :class => "right", :confirm => "You sure?" %>

<h2><%= @recipe.name %></h2>
<%= @recipe.course %><br>
<%= @recipe.cooktime %> minutes<br>
Serves: <%= @recipe.servingsize %><br>
<%= @recipe.instructions %><br>
<%= image_tag(@recipe.image) %><br>